main/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from main.views import NotificationCheckView, PromptView, ShareView, \
    VotingBlockShareView, MobilePledgeView


urlpatterns = patterns(
    "main.views",
    url(r"^$", "index", name="index"),
    url(r"^demo_transaction_error$", "demo_transaction_error"),
    url(r"^fetch_me$", "fetch_me", name="fetch_me"),
    url(r"^fetch_friends$", "fetch_friends", name="fetch_friends"),
    url(r"^my_vote$", "my_vote", name="my_vote"),
    url(r"^my_vote/pledge$", "my_vote_pledge", name="my_vote_pledge"),
    url(r"^my_vote/vote$", "my_vote_vote", name="my_vote_vote"),
    url(r"^pledge$", "pledge", name="pledge"),
    url(r"^unpledge$", "_unpledge", name="unpledge"),
    url(r"^submit_pledge$", "submit_pledge", name="submit_pledge"),
    url(r"^wont_vote$", "wont_vote", name="wont_vote"),
    url(r"^missions$", "mission", name="missions"),
    url(r"^fetch_updated_batches$", "fetch_updated_batches", name="fetch_updated_batches"),
    url(r"^mark_batch_invited$", "mark_batch_invited", name="mark_batch_invited"),
    url(r"^mark_individual_invited$", "mark_individual_invited", name="mark_individual_invited"),
    url(r"^single_user_invited$", "single_user_invited", name="single_user_invited"),
    url(r"^friends_list$", "friends_list"),
    url(r"^unsubscribe$", "unsubscribe", name="unsubscribe"),
    url(r"^appunsubscribe$", "unsubscribe", name="appunsubscribe"),
    url(r"^invite_friends_2$", "invite_friends_2", name="invite_friends_2"),
    url(r"^invite_friends_2/(?P<section>\w+)$", "invite_friends_2", name="invite_friends_2"),
    url(r"^invite_friends_2_page/(?P<section>\w+)$", "invite_friends_2_page", name="invite_friends_2_page"),
    url(r"^mission$", "mission", name="mission"),
    url(r"^mission/(?P<batch_type>\d+)", "mission", name="mission"),
    url(r"^mission_friends_page/(?P<batch_type>\d+)", "mission_friends_page", name="mission_friends_page"),
    url(r"^mark_mission_batch_invited/(?P<batch_type>\d+)", "mark_mission_batch_invited", name="mark_mission_batch_invited"),
    url(r"^voting_blocks$", "voting_blocks", name="voting_blocks"),
    url(r"^voting_blocks_search", "voting_blocks_search", name="voting_blocks_search"),
    url(r"^voting_blocks/create$", "voting_blocks_create", name="voting_blocks_create"),
    url(r"^voting_blocks/(?P<id>\d+)(?:/section/(?P<section>\w+))?$", "voting_blocks_item", name="voting_blocks_item"),
    url(r"^voting_blocks/(?P<id>\d+)/join$", "voting_blocks_item_join", name="voting_blocks_item_join"),
    url(r"^voting_blocks/(?P<id>\d+)/leave$", "voting_blocks_item_leave", name="voting_blocks_item_leave"),
    url(r"^voting_blocks/(?P<id>\d+)/mark_individual_invited$", "voting_blocks_item_mark_individual_invited", name="voting_blocks_item_mark_individual_invited"),
    url(r"^voting_blocks/(?P<id>\d+)/mark_batch_invited$", "voting_blocks_item_mark_batch_invited", name="voting_blocks_item_mark_batch_invited"),
    url(r"^voting_blocks/(?P<id>\d+)/section/(?P<section>\w+)/page$", "voting_blocks_item_page", name="voting_blocks_item_page"),
)

urlpatterns += patterns(
    "",
    url(r"^mobile$",
        MobilePledgeView.as_view(),
        name="mobile",
    ),
    url(r"^prompt$",
        PromptView.as_view(),
        name="prompt"
    ),
    url(r"^share$",
        ShareView.as_view(),
        name="share"
    ),
    url(r"^nowunsubscribed$",
        TemplateView.as_view(template_name="now_unsubscribed.html")),
    url(r"^voterreg_invite$",
        TemplateView.as_view(template_name="voterreg_invite.html"),
        name="voterreg_invite"),
    url(r"^no_cookies$",
        TemplateView.as_view(template_name="no_cookies.html"),
        name="no_cookies"),
    url(r"^block/(?P<pk>\d+)$",
        VotingBlockShareView.as_view(),
        name="voting_block_share"),
    url(r"^notifications$",
        NotificationCheckView.as_view(),
        name="notifications"),
)

voterreg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from main.views import OGObjectView


admin.autodiscover()

urlpatterns = patterns('',
    (r'', include("main.urls", namespace="main")),
    url(r'staticpages/(?P<page_name>.*)', "staticpages.views.index", name="staticpages"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^og_pledge', OGObjectView.as_view(template_name='pledge/index.html'), name="pledge_object"),
    url(r'^og_vote', OGObjectView.as_view(template_name='vote/index.html'), name="vote_object"),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^404', TemplateView.as_view(template_name='404.html')),
        url(r'^500', TemplateView.as_view(template_name='500.html')),
    )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base-error.html
{% load i18n %}
{% load static from staticfiles %}
{% load url from future %}

<!doctype html>
<html class="no-js" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block meta_title %}Fight for the Future{% endblock %}</title>
        <meta name="viewport" content="width=device-width">
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.modal.css' %}">
        <link rel="stylesheet" href="{% static 'css/error.css' %}">
        {% block css %}{% endblock %}
        <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-35232596-1']);
            _gaq.push(['_trackPageview']);
            var _kmq = _kmq || [];
            var _kmk = _kmk || '{{ KM_CODE }}';
            setTimeout(function() {
                function addScript(src) {
                    var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true; sc.src = src;
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
                }
                addScript(('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js');
                addScript('//i.kissmetrics.com/i.js');
                addScript('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
            }, 1);
            {% if my_uid %}_kmq.push(['identify', '{{ my_uid }}']);{% endif %}
            {% if traffic_source %}_kmq.push(['record', 'Traffic source: {{ traffic_source }}']);{% endif %}
        </script>
    </head>
    <body>

        <div id="error">
            <h1>Vote With Friends</h1>
            <h2>{% block error_type %}Error{% endblock error_type %}</h2>
            <h3>{% block header %}Uh oh!{% endblock header %}</h3>
            {% block copy %}
                <p>Pus-ghettios!</p>
            {% endblock copy %}
        </div>

    </body>
</html>

templates/base-mobile.html
<!doctype html>

{% load i18n %}
{% load static from staticfiles %}
{% load url from future %}

<html xmlns:fb="http://ogp.me/ns/fb#" class="no-js" lang="en">
    <head>
        {% if INSTALLATION == "production" %}<script src="//cdn.optimizely.com/js/21249520.js"></script>{% endif %}
        <meta charset="utf-8">
        <title>{% block meta_title %}Fight for the Future{% endblock %}</title>
        <meta name="description" content="{% block meta_description %}Fight for the Future{% endblock %}">
        <meta name="author" content="Fight for the Future">
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'css/mobile.css' %}">
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-35232596-1']);
            _gaq.push(['_trackPageview']);
            var _kmq = _kmq || [];
            var _kmk = _kmk || '{{ KM_CODE }}';
            setTimeout(function() {
                function addScript(src) {
                    var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true; sc.src = src;
                    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
                }
                addScript(('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js');
                addScript('//i.kissmetrics.com/i.js');
                addScript('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
            }, 1);
            {% if my_uid %}_kmq.push(['identify', '{{ my_uid }}']);{% endif %}
            {% if traffic_source %}_kmq.push(['record', 'Traffic source: {{ traffic_source }}']);{% endif %}
        </script>
    </head>
    <body>
        {% block main %}{% endblock main %}
        <div id="fb-root"></div>
        <script src="https://connect.facebook.net/en_US/all.js#xfbml=1&amp;appId={{ FACEBOOK_APP_ID }}"></script>
        <script src="{% static 'js/jquery.js' %}"></script>
        <script>
            var app = {
                'PLEDGE_ACTION_URL': '{{ OG_URL }}',
                'VOTE_OBJ_URL': '{{ VOTE_OBJ }}',
                'APP_ID': '{{ FACEBOOK_APP_ID }}',
                'APP_SHARE_URL': '{{ APP_SHARE_URL }}',
            };
        </script>
        <script src="{% static 'js/mobile.js' %}"></script>
    </body>
</html>

templates/base.html
<!doctype html>

{% load i18n %}
{% load static from staticfiles %}
{% load url from future %}

<html xmlns:fb="http://ogp.me/ns/fb#" class="no-js" lang="en">
  <head>
    {% if INSTALLATION == "production" %}<script src="//cdn.optimizely.com/js/21249520.js"></script>{% endif %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block meta_title %}Fight for the Future{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}Fight for the Future{% endblock %}">
    <meta name="author" content="Fight for the Future">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.modal.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/prompt.css' %}">
    {% block css %}{% endblock %}
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-35232596-1']);
      _gaq.push(['_trackPageview']);
      var _kmq = _kmq || [];
      var _kmk = _kmk || '{{ KM_CODE }}';
      setTimeout(function() {
          function addScript(src) {
            var sc = document.createElement('script'); sc.type = 'text/javascript'; sc.async = true; sc.src = src;
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(sc, s);
          }
          addScript(('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js');
          addScript('//i.kissmetrics.com/i.js');
          addScript('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
        }, 1);
      {% if my_uid %}_kmq.push(['identify', '{{ my_uid }}']);{% endif %}
      {% if traffic_source %}_kmq.push(['record', 'Traffic source: {{ traffic_source }}']);{% endif %}
    </script>
  </head>
  <body>
    <div id="fb-root"></div>

    <div id="container"><div id="container-inner">
    <header>
        <div class="inner cf">

            <div class="logo">
                <h1>Vote for the Internet</h1>
                <p>Get more of your friends to vote than you ever thought possible.</p>
            </div>

            <div class="score cf">
                <h2>{{ fb_user.first_name }} {{ fb_user.last_name }}</h2>
                <figure>
                    <img src="{{ fb_user.pic }}" />
                </figure>
                <ul class="user">
                    <li class="{{ vwf_user.pledged|lower }}">
                        <a href="{% url 'main:my_vote_pledge' %}">
                            {% if vwf_user.pledged %}Pledged{% else %}Hasn't Pledged{% endif %}
                        </a>
                    </li>
                    <li class="{{ vwf_user.voted|lower }}">
                        <a href="{% url 'main:my_vote_vote' %}">
                            {% if vwf_user.voted %}Voted{% else %}Hasn't Voted{% endif %}
                        </a>
                    </li>
                </ul>
                <ul class="friends">
                    <li class="invited">
                        <a href="{% url 'main:invite_friends_2' 'invited' %}">
                            <strong class="num">{{ vwf_user.friends.invited.count }}</strong>Friends Invited
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'main:invite_friends_2' 'pledged' %}">
                            <strong class="num">{{ vwf_user.friends.pledged.count }}</strong>Friends Pledged
                        </a>
                    </li>
                    <li class="voted">
                        <a href="{% url 'main:invite_friends_2' 'voted' %}">
                            <strong class="num">{{ vwf_user.friends.voted.count }}</strong>Friends Voted
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </header>

      {% block nav %}
          <ul id="nav">
            <li><a href="{% url 'main:missions' %}" {% if page == "missions" %}class="selected"{% endif %}>MISSIONS</a></li>
            <li><a href="{% url 'main:my_vote' %}?force" {% if page == "my_vote" %}class="selected"{% endif %}>MY VOTE</a></li>
            <li><a href="{% url 'main:voting_blocks' %}" {% if page == "voting_blocks" %}class="selected"{% endif %}>VOTING BLOCKS</a></li>
            <li><a href="{% url 'main:invite_friends_2' %}" {% if page == "friends" %}class="selected"{% endif %}>MY FRIENDS</a></li>
          </ul>
      {% endblock nav %}
    <ul class="notification">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
        {% endfor %}
    </ul>
    <div class="content cf">
        <ul id="banner">
            <li><a href="#" data-message-url="{% block banner_message_url %}{{ sharing_url }}{% url 'main:share' %}{% endblock banner_message_url %}">Invite Friends</a></li>
            <li><a href="#" data-timeline-url="{% block banner_timeline_url %}{{ sharing_url }}{% url 'main:share' %}{% endblock banner_timeline_url %}">Post On Timeline</a></li>
        </ul>
        {% block content %}{% endblock %}
    </div>
    <div class="days-left">
      
      <span class="regular large">{{num_days_left}}</span> 
      {% comment %}Translators: this is the word 'days' as used in 'x days to the election'. Use singular (we add s automatically){% endcomment %}
      <span class="cursive">{% blocktrans %}day{% endblocktrans%}{{ num_days_left|pluralize }}</span><br>
      {% comment %}Translators: this are the words "TIL THE" in "28 days till the election"{% endcomment %}
      <span class="regular">TIL THE</span><br>
      {% comment %}Translators: this is the word "election" in "28 days till the election"{% endcomment %}
      <span class="regular">ELECTION</span>
    </div>
    <a class="invite-friends" href="javascript:void(0)">
      <i class="icon-invite"></i>
      <span>Invite<br>Friends</span>
    </a>
    <a class="feedback" href="mailto:team+vwf@fightforthefuture.org">Feedback?</a>
    {% block modals %}{% endblock %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.modal.js' %}"></script>
    <script src="{% static 'js/prompt.js' %}"></script>
    <script src="https://connect.facebook.net/en_US/all.js#xfbml=1&amp;appId={{ FACEBOOK_APP_ID }}"></script>
    <script>
      var FACEBOOK_CANVAS_PAGE = "{{FACEBOOK_CANVAS_PAGE}}";
      var PROMPT_URL = "{% url 'main:prompt' %}";
      var SINGLE_USER_INVITED_URL = "{% url 'main:single_user_invited' %}";
      var NOTIFICATION_URL = "{% url 'main:notifications' %}";
      var DEBUG_APP_REQUESTS = {% if DEBUG_APP_REQUESTS %}true{% else %}false{% endif %};
      FB.init({
        appId  : '{{FACEBOOK_APP_ID}}',
        frictionlessRequests: true
      });
      FB.Canvas.setAutoGrow();
    </script>
    <script src="{% static 'js/base.js' %}"></script>
    {% block scripts %}{% endblock %}
    </div></div>
  </body>
</html>

templates/notifications.html
{% if messages %}
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|safe }}</li>
    {% endfor %}
{% endif %}

templates/unsupported_ua.html
{% extends "base-error.html" %}

{% load url from future %}

{% block meta_title %}Unsupport Browser - {{ block.super }}{% endblock meta_title %}

{% block error_type %}Uh oh!{% endblock error_type %}

{% block header %}Unsupported Browser{% endblock header %}

{% block copy %}
    <p>Unfortunately, we are unable to support the web browser that you're currently using. If possible, please upgrade to the most recent version. If you're unable to do so, would you mind trying a different, supported browser?</p>
    <p>Some of our favorites:</p>
    <ul>
        <li><a href="http://www.mozilla.org/en-US/firefox/new/" target="_parent">Mozilla Firefox</a></li>
        <li><a href="https://www.google.com/intl/en/chrome/browser/" target="_parent">Google Chrome</a></li>
        <li><a href="http://www.apple.com/safari/" target="_parent">Apple Safari</a></li>
        <li><a href="http://www.opera.com/browser/" target="_parent">Opera</a></li>
    </ul>
    <p>Thanks for understanding!</p>
{% endblock copy %}