main/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from main.views import NotificationCheckView, PromptView, ShareView, \
    VotingBlockShareView, MobilePledgeView


urlpatterns = patterns(
    "main.views",
    url(r"^$", "index", name="index"),
    url(r"^demo_transaction_error$", "demo_transaction_error"),
    url(r"^fetch_me$", "fetch_me", name="fetch_me"),
    url(r"^fetch_friends$", "fetch_friends", name="fetch_friends"),
    url(r"^my_vote$", "my_vote", name="my_vote"),
    url(r"^my_vote/pledge$", "my_vote_pledge", name="my_vote_pledge"),
    url(r"^my_vote/vote$", "my_vote_vote", name="my_vote_vote"),
    url(r"^pledge$", "pledge", name="pledge"),
    url(r"^unpledge$", "_unpledge", name="unpledge"),
    url(r"^submit_pledge$", "submit_pledge", name="submit_pledge"),
    url(r"^wont_vote$", "wont_vote", name="wont_vote"),
    url(r"^missions$", "mission", name="missions"),
    url(r"^fetch_updated_batches$", "fetch_updated_batches", name="fetch_updated_batches"),
    url(r"^mark_batch_invited$", "mark_batch_invited", name="mark_batch_invited"),
    url(r"^mark_individual_invited$", "mark_individual_invited", name="mark_individual_invited"),
    url(r"^single_user_invited$", "single_user_invited", name="single_user_invited"),
    url(r"^friends_list$", "friends_list"),
    url(r"^unsubscribe$", "unsubscribe", name="unsubscribe"),
    url(r"^appunsubscribe$", "unsubscribe", name="appunsubscribe"),
    url(r"^invite_friends_2$", "invite_friends_2", name="invite_friends_2"),
    url(r"^invite_friends_2/(?P<section>\w+)$", "invite_friends_2", name="invite_friends_2"),
    url(r"^invite_friends_2_page/(?P<section>\w+)$", "invite_friends_2_page", name="invite_friends_2_page"),
    url(r"^mission$", "mission", name="mission"),
    url(r"^mission/(?P<batch_type>\d+)", "mission", name="mission"),
    url(r"^mission_friends_page/(?P<batch_type>\d+)", "mission_friends_page", name="mission_friends_page"),
    url(r"^mark_mission_batch_invited/(?P<batch_type>\d+)", "mark_mission_batch_invited", name="mark_mission_batch_invited"),
    url(r"^voting_blocks$", "voting_blocks", name="voting_blocks"),
    url(r"^voting_blocks_search", "voting_blocks_search", name="voting_blocks_search"),
    url(r"^voting_blocks/create$", "voting_blocks_create", name="voting_blocks_create"),
    url(r"^voting_blocks/(?P<id>\d+)(?:/section/(?P<section>\w+))?$", "voting_blocks_item", name="voting_blocks_item"),
    url(r"^voting_blocks/(?P<id>\d+)/join$", "voting_blocks_item_join", name="voting_blocks_item_join"),
    url(r"^voting_blocks/(?P<id>\d+)/leave$", "voting_blocks_item_leave", name="voting_blocks_item_leave"),
    url(r"^voting_blocks/(?P<id>\d+)/mark_individual_invited$", "voting_blocks_item_mark_individual_invited", name="voting_blocks_item_mark_individual_invited"),
    url(r"^voting_blocks/(?P<id>\d+)/mark_batch_invited$", "voting_blocks_item_mark_batch_invited", name="voting_blocks_item_mark_batch_invited"),
    url(r"^voting_blocks/(?P<id>\d+)/section/(?P<section>\w+)/page$", "voting_blocks_item_page", name="voting_blocks_item_page"),
)

urlpatterns += patterns(
    "",
    url(r"^mobile$",
        MobilePledgeView.as_view(),
        name="mobile",
    ),
    url(r"^prompt$",
        PromptView.as_view(),
        name="prompt"
    ),
    url(r"^share$",
        ShareView.as_view(),
        name="share"
    ),
    url(r"^nowunsubscribed$",
        TemplateView.as_view(template_name="now_unsubscribed.html")),
    url(r"^voterreg_invite$",
        TemplateView.as_view(template_name="voterreg_invite.html"),
        name="voterreg_invite"),
    url(r"^no_cookies$",
        TemplateView.as_view(template_name="no_cookies.html"),
        name="no_cookies"),
    url(r"^block/(?P<pk>\d+)$",
        VotingBlockShareView.as_view(),
        name="voting_block_share"),
    url(r"^notifications$",
        NotificationCheckView.as_view(),
        name="notifications"),
)

voterreg/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from main.views import OGObjectView


admin.autodiscover()

urlpatterns = patterns('',
    (r'', include("main.urls", namespace="main")),
    url(r'staticpages/(?P<page_name>.*)', "staticpages.views.index", name="staticpages"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^og_pledge', OGObjectView.as_view(template_name='pledge/index.html'), name="pledge_object"),
    url(r'^og_vote', OGObjectView.as_view(template_name='vote/index.html'), name="vote_object"),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^404', TemplateView.as_view(template_name='404.html')),
        url(r'^500', TemplateView.as_view(template_name='500.html')),
    )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/forms.py
from django import forms
from models import WONT_VOTE_REASONS, VotingBlock
from django.forms.util import ErrorList

class WontVoteForm(forms.Form):
    wont_vote_reason = forms.ChoiceField(
        widget=forms.RadioSelect, choices=WONT_VOTE_REASONS)

class VotingBlockForm(forms.ModelForm):

    def clean(self):
        cleaned_data = super(VotingBlockForm, self).clean()
        name = cleaned_data.get("organization_name")
        website = cleaned_data.get("organization_website")
        privacy_policy = cleaned_data.get("organization_privacy_policy")
        if name or website or privacy_policy:
            if not name:
                self.errors['organization_name'] = self.errors.get('organization_name') or  ErrorList()
                self.errors['organization_name'].append('Field is Required.')
            if not website:
                self.errors['organization_website'] = self.errors.get('organization_website') or  ErrorList()
                self.errors['organization_website'].append('Field is Required.')
            if not privacy_policy:
                self.errors['organization_privacy_policy'] = self.errors.get('organization_privacy_policy') or  ErrorList()
                self.errors['organization_privacy_policy'].append('Field is Required.')
        return cleaned_data

    class Meta:
        model = VotingBlock
        fields = ('name', 'description', 'icon', 'organization_name', 'organization_website', 'organization_privacy_policy')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Voting block name'}),
            'description': forms.TextInput(attrs={'placeholder': 'Description / share text'}),
            'icon': forms.FileInput(attrs={'data-change-text': 'Change Image', 'data-set-text': 'Select Image'}),
            'organization_name': forms.TextInput(attrs={'placeholder': '"Organization Name"'}),
            'organization_website': forms.TextInput(attrs={'placeholder': 'Website'}),
            'organization_privacy_policy': forms.TextInput(attrs={'placeholder': 'Link to Privacy Policy'})
        }

main/views.py
import facebook
from os import environ
import requests
import urllib
from urlparse import urlparse
import sys
from django.db import IntegrityError
from django.db.models import Q, Count
from django.contrib import messages
from django.conf import settings
from django.core.urlresolvers import resolve
from django.shortcuts import render_to_response, redirect
from django.template.loader import render_to_string
from django.template.context import RequestContext
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from django.views.decorators.csrf import csrf_exempt
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import NoReverseMatch, reverse
from django.http import Http404, HttpResponse, HttpResponseNotAllowed, \
    HttpResponseRedirect
from tasks import fetch_fb_friends, update_friends_of
from decorators import render_json
from voterapi import fetch_voter_from_fb_profile, correct_voter
from models import User, FriendshipBatch, BATCH_REGULAR, VotingBlock, \
    VotingBlockMember, VotingBlockFriendship, InvitedToBlock
from datetime import datetime, date, time, timedelta
from fb_utils import FacebookProfile, opengraph_url, online_friends
from django.core.mail import EmailMultiAlternatives
from models import BATCH_NEARBY, Friendship, BADGE_CUTOFFS
import logging
import forms

class OGObjectView(TemplateView):
    """
    The view used to serve the OpenGraph objects published whenever a user
    pledges to vote.
    """

    def get_context_data(self, **kwargs):
        context = super(OGObjectView, self).get_context_data(**kwargs)
        context['base_url'] = settings.BASE_URL
        context['canvas_url'] = settings.FACEBOOK_CANVAS_PAGE
        context['facebook_app_id'] = settings.FACEBOOK_APP_ID

        environment = environ.get("RACK_ENV", 'dev')
        namespace_map = {
            'dev': '-dev',
            'staging': '-stag',
            'production': '',
        }
        context['og_namespace'] = namespace_map[environment]

        return context


class ShareView(TemplateView):
    """
    The view used to share with other apps
    """
    template_name = 'share.html'

    def get_context_data(self, **kwargs):
        context = super(ShareView, self).get_context_data(**kwargs)
        context['base_url'] = settings.BASE_URL
        context['canvas_url'] = settings.FACEBOOK_CANVAS_PAGE
        context['share_url'] = settings.SHARING_URL
        context['facebook_app_id'] = settings.FACEBOOK_APP_ID
        return context


class VotingBlockShareView(DetailView):
    """

    """
    model = VotingBlock
    template_name = 'voting_blocks_share.html'
    context_object_name = 'block'

    def get_context_data(self, **kwargs):
        context = super(VotingBlockShareView, self).get_context_data(**kwargs)
        context['facebook_app_id'] = settings.FACEBOOK_APP_ID
        context['canvas_url'] = settings.FACEBOOK_CANVAS_PAGE
        return context


class NotificationCheckView(TemplateView):
    template_name = 'notifications.html'


class PromptView(TemplateView):
    """
    View for a modal window prompting users to invite
    """
    template_name = 'prompt.html'

    def get(self, request, *args, **kwargs):
        """
        Marks the user as having seen the initial prompt if friends were
        returned by self.get_context_data
        """
        context = self.get_context_data(params=kwargs)
        if context['friends']:
            self._user_obj.seen_initial_prompt = True
            self._user_obj.save()
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        """
        Adds metadata for a prompt based on the `type` keyword argument.
        """
        self._user_obj = User.objects.get(fb_uid=self.request.facebook["uid"])
        context = super(PromptView, self).get_context_data(**kwargs)
        context['only_show_friends'] = self.request.GET.get('only_friends', None) == 'true'
        prompt_type = self.request.GET.get('type', None)
        if prompt_type == 'online':
            context.update(self._online())
        else:
            context.update(self._online())
        return context

    def _online(self):
        """
        Returns metadata for a prompt featuring online friends.
        """
        user = self._user_obj
        not_invited = user.friends.personally_invited(status=False)
        online = not_invited.filter(fb_uid__in=online_friends(self.request))
        selection = online.order_by('?')[:4]
        return {
            'friends': selection,
            'title': 'Will your friends vote?',
            'description': (
                "It's in your hands. Here are four friends who are likely "
                "voters.  They're online right now, and some of them may be "
                "able to vote early.  Can you get them to vote?"
            ),
            'attributes': {
                'online': True,
                'likely_voter': True,
                'early_voting': True,
            }
        }


def _post_index(request):
    query_string = request.META["QUERY_STRING"]
    redirect_uri = settings.FACEBOOK_CANVAS_PAGE
    if query_string:
        redirect_uri += ("?" + query_string)
    signed_request = request.POST["signed_request"]
    data = facebook.parse_signed_request(
        signed_request,
        settings.FACEBOOK_APP_SECRET)
    if not data.get("user_id"):
        scope = ["user_birthday", "user_location", "friends_birthday,"
                 "friends_hometown", "friends_location", "email",
                 "publish_actions", "friends_online_presence"]
        auth_url = facebook.auth_url(settings.FACEBOOK_APP_ID,
                                     redirect_uri, scope)
        markup = ('<script type="text/javascript">'
                  'top.location.href="%s"</script>' % auth_url)
        return HttpResponse(markup)
    return None


def _main_content_context(user):
    return {
        "registered": user.registered,
        "pledged": user.pledged,
        "invited_friends": user.invited_friends
    }


def _index_redirect(user, query_string=""):
    if query_string:
        query_string = "?" + query_string
    if user.wont_vote:
        return redirect(reverse("main:invite_friends_2") + query_string)
    else:
        return redirect(reverse("main:my_vote") + query_string)


def _fetch_fb_friends(request):
    fb_uid = request.facebook["uid"]
    access_token = request.facebook["access_token"]
    user = User.objects.get(fb_uid=fb_uid)
    if user.friends_need_fetching():
        user.update_friends_fetch()
        user.save()
        fetch_fb_friends.delay(fb_uid, access_token)


def _unpledge(request):
    if request.method == 'POST':
        user = User.objects.get(fb_uid=request.facebook["uid"])
        user.date_pledged = None
        user.save()
        update_friends_of.delay(user.id)
        messages.add_message(
            request, messages.INFO,
            # Translators: message displayed to users when they unpledge
            _("Sorry to hear that you're no longer pledging to vote.")
        )
        return redirect('main:my_vote')
    return HttpResponseNotAllowed()


@csrf_exempt
def index(request):
    if request.method == "POST":
        response = _post_index(request)
        if response:
            return response
    request.session['after'] = request.REQUEST.get("after", None)
    block_id = request.REQUEST.get("block", None)
    if not block_id:
        try:
            itb = InvitedToBlock.objects.get(fb_uid=request.facebook["uid"])
            block_id = itb.voting_block_id
            itb.delete()
        except:
            pass
    request.session['block_id'] = block_id
    request.session.modified = True
    user = User.objects.get(fb_uid=request.facebook["uid"])
    query_string = request.META["QUERY_STRING"]
    if user.data_fetched:
        target_url = request.GET.get("target", None)
        if target_url:
            try:
                return redirect(target_url)
            except NoReverseMatch:
                raise Http404
        else:
            return _index_redirect(user, query_string)
    return render_to_response(
        "loading.html",
        context_instance=RequestContext(request))


def my_vote(request):
    user = User.objects.get(fb_uid=request.facebook["uid"])
    after = request.session.get('after', None)
    block_id = request.session.get('block_id', None)
    force = 'force' in request.GET

    if not user.pledged:
        return redirect('main:my_vote_pledge')

    if not user.voted or (user.voted and force):
        return redirect('main:my_vote_vote')

    elif user.pledged and user.voted and after:
        return redirect(after)

    elif user.pledged and user.voted and block_id:
        return redirect(reverse("main:voting_blocks_item", args=[block_id,]))

    return redirect('main:invite_friends_2')


def my_vote_pledge(request):
    if not request.facebook:
        # assuming optimizely server.
        user = { "pledged": False }
    else:
        user = User.objects.get(fb_uid=request.facebook["uid"])
        if request.GET.get("from_widget", False):
            user.registered = True
            user.used_registration_widget = True
            user.save()
            update_friends_of.delay(user.id)
            messages.add_message(
                request, messages.INFO,
                # Translators: message displayed to users in green bar when they register to vote
                _("Thank you for registering to vote!"))
    voting_block = _voting_block_from_session(request.session)
    return render_to_response("my_vote_pledge.html", {
        'page': 'my_vote',
        'section': 'pledge',
        'user': user,
        'voting_block': voting_block
    }, context_instance=RequestContext(request))

def _voting_block_from_session(session):
    block_id = session.get("block_id", None)
    if block_id:
        try:

main/templates/_base_modal.html
<div id="{{modal_id}}" class="modal hide fade" role="dialog" aria-labelledby="title" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="title">{% block title %}{% endblock %}</h3>
  </div>
  <div class="modal-body">{% block body %}{% endblock %}</div>
  <div class="modal-footer">{% block footer %}{% endblock %}</div>
</div>

main/templates/_invite_friends_buttons.html
<a href="javascript:void(0)" id="load_more_friends" class="load-more">
  {% comment %}Translators: text of button that allows user to load more friends{% endcomment %}
  <span id="load_more_label">Load More Friends</span>
  {% comment %}Translators: text of button that indicates more friends are loading{% endcomment %}
  <span id="loading_label" style="display: none">Friends Loading...</span>
</a>

main/templates/_wont_vote_modal.html
{% extends "_base_modal.html" %}

{% load i18n %}
{% load url from future %}

{% comment %}Translators: title of modal asking users why they aren't voting{% endcomment %}
{% block title %}{% trans "Why not vote?" %}{% endblock %}

{% block body %}

    {% comment %}Translators: introduction to list of reasons the user might not be voting{% endcomment %}
    <p>{% trans "I won't vote because:" %}</p>
    <form class="wont_vote" action="{% url 'main:wont_vote' %}" method="POST">
        {% csrf_token %}
        {{ wont_vote_form.wont_vote_reason }}
        <button class="btn btn-large btn-green">
            <i class="icon-ok"></i> 
            {% comment %}Translators: submit button when user is giving a reason for not voting{% endcomment %}
            {% trans "This is why I'm not voting" %}
        </button>
    </form>
{% endblock %}

main/templates/cookies_test.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load url from future %}

{% block nav %}{% endblock nav %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/safari.css' %}">
{% endblock %}

{% block content %}
<div class="main-content cf">
  <div id="content" style="display: none">
    <div class="main-content-message">

      {% comment %}Translators: title on page displayed to Safari users that forces them to interact with the page{% endcomment %}
      <h2>{% trans "Help us get more Americans to vote than ever before." %}</h2>
    </div>
    <div class="main-content-message">

      {% comment %}Translators: text of button on page displayed to Safari users that forces them to interact with the page{% endcomment %}
      <a href="{% url 'main:no_cookies' %}?{{query_string}}" target="_blank" class="btn btn-large btn-green">{% trans "Get started!" %}</a>

    </div>
  </div>
</div>
{% endblock %}

{% block scripts %}
  <script type="text/javascript">
    if (document.cookie.length > 1) {
      window.location.replace({% if inner_query_string %}"/?{{inner_query_string}}"{% else %}"/"{% endif %});
    }
    else {
      $("#content").show();
    }
  </script>
{% endblock %}

main/templates/invite_friends_2.html
{% extends "base.html" %}

{% load i18n %}
{% load static from staticfiles %}
{% load url from future %}


{% block css %}
    
{% endblock css %}


{% block content %}

    <ul class="filters">

        {% comment %}Translators: group of friends the user hasn't yet invited to the app{% endcomment %}
        <li{% if section == "not_invited" %} class="selected"{% endif %} id="uninvited_friends"><a href="{% url 'main:invite_friends_2' 'not_invited' %}">Not Invited <span class="count">(<span class="num">{{ num_uninvited }}</span>)</span></a></li>

        {% comment %}Translators: group of friends the user has invited to the app but who have not yet pledged{% endcomment %}
        <li{% if section == "not_pledged" %} class="selected"{% endif %} id="not_pledged_friends"><a href="{% url 'main:invite_friends_2' 'not_pledged' %}">Not pledged <span class="count">(<span class="num">{{ num_not_pledged }}</span>)</span></a></li>

        {% comment %}Translators: group of friends the have registered to vote{% endcomment %}
        <li{% if section == "registered" %} class="selected"{% endif %}><a href="{% url 'main:invite_friends_2' 'registered' %}">Registered <span class="count">({{ num_registered }})</span></a></li>

        {% comment %}Translators: group of friends who have pledged to vote{% endcomment %}
        <li{% if section == "pledged" %} class="selected"{% endif %}><a href="{% url 'main:invite_friends_2' 'pledged' %}">Pledged <span class="count">({{ num_pledged }})</span></a></li>

        {% comment %}Translators: group of friends that have voted{% endcomment %}
        <li{% if section == "voted" %} class="selected"{% endif %}><a href="{% url 'main:invite_friends_2' 'voted' %}">Voted <span class="count">({{ num_voted }})</span></a></li>

    </ul>

    <div class="main-content cf" id="friends">
        {% include "_invite_friends_page.html" %}
        {% if friends %}
        {% include "_invite_friends_buttons.html" %}
        {% endif %}
    </div>

{% endblock %}


{% block scripts %}
    <script>
        var MARK_INVITED_URL = "{% url 'main:mark_individual_invited' %}";
        var SHARE_LINK = "{{ share_url }}{% url 'main:share' %}";
        var FACEBOOK_CANVAS_PAGE = "{{FACEBOOK_CANVAS_PAGE}}";
        var LOAD_MORE_URL = "{% url 'main:invite_friends_2_page' section %}";
    </script>
    <script src="{% static 'js/invite_friend_grid.js' %}"></script>

    {% if not vwf_user.seen_initial_prompt or force_prompt %}
        <script type="text/javascript">
            jQuery(function(){
                prompt.modal();
            })
        </script>
    {% endif %}

{% endblock %}

main/templates/register.html
{% extends "friends_listing_base.html" %}

{% load i18n %}
{% load static from staticfiles %}
{% load url from future %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block topcontent %}
<div class="main-content-message">

    {% comment %}Translators: tagline of page where users are told we can't find a voter registration record for them{% endcomment %}
    <h2>Are you registered to vote?  We can't find a registration for you based on your Facebook info.</h2>

    {% comment %}Translators: description of the data we used to see if the user was registered to vote{% endcomment %}
    <p>({% trans "We searched for:" %} {{ name }}{% if location %} / {{location}}{% endif %}{% if birthday %} / {{birthday}}{% endif %})</p>

</div>
<div class="main-content-buttons">

  {% comment %}Translators: text of button users click to confirm that they are registered to vote, despite our records saying otherwise{% endcomment %}
  <a id="already-registered" href="javascript:void(0)" class="btn btn-large btn-blue">{% trans "I'm Registered" %}</a>

  {% comment %}Translators: text of button users click to visit internetvotes.org to register to vote{% endcomment %}
  <a href="http://www.theinternetvotes.org" target="internetvotes" class="btn btn-large btn-green"><i class="icon-ok"></i> Register Now</a>

  <br/>

  {% comment %}Translators: explanation that a link opens in a new window{% endcomment %}
  <span class="note">{% trans "(Opens in a new window)" %}</span>

</div>
<div class="main-content-message">

  {% comment %}Translators: text of button users click to say they aren't eligible to vote{% endcomment %}
  <a id="not-eligible" href="javascript:void(0)">I'm not eligible</a>

</div>
<div class="main-content-extra">

  {% comment %}Translators: explanation that it's okay if users re-register to vote if they are unsure{% endcomment %}
  <span>{% blocktrans %}Not sure if you are registered? If you're unsure, It’s always best to re-register to update your address and info. Note: we match user information with voter records. This information may not be up-to-date, and we may not have enough data to make a match.{% endblocktrans %}</span>

</div>
{% endblock %}

{% block scripts %}
{{ block.super }}
<script>
  var ACTUALLY_REGISTERED_URL = "{% url 'main:actually_registered' %}";
  var WONT_VOTE_URL = "{% url 'main:wont_vote' %}";
</script>
<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock %}

main/templates/share.html
{% load staticfiles %}
{% load thumbnail %}
{% load url from future %}
<html>
    <head>
        <title>Redirecting</title>
        <meta property="fb:app_id" content="{{ facebook_app_id }}" />
        <meta property="og:title" content="Vote with Friends" />
        <meta property="og:description" content="Look up your friends' real voting history and make them *promise* to vote on election day." />
        <meta property="og:image" content="https://fbcdn-photos-a.akamaihd.net/photos-ak-snc7/v85006/154/152013131606602/app_104_152013131606602_2031919809.png" />
        <meta property="og:url" content="{{ share_url }}{% url 'main:share' %}" />
        <meta property="og:type" content="website" />
    </head>
    <body>
        <script type="text/javascript">
            window.top.location = 'http://apps.facebook.com/votewithfriends';
        </script>
    </body>
</html>

main/templates/voting_blocks.html
{% extends "base.html" %}

{% load i18n %}
{% load static from staticfiles %}
{% load url from future %}
{% load thumbnail %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'css/voting_blocks.css' %}">
{% endblock css %}

{% block content %}
<div class="voting-blocks white-box cf">
    {% if not voting_block_note %}
    <div class="note">
        <p><strong>Before you get started!</strong>  Three things to know about voting blocks:</p>
        <p><strong>1)</strong> A voting block is a way to organize specific groups to vote (for example: "First Baptist Church of Detroit, MI", "Coffee Cafe Staff", "Fans of RugLovers.com") or to mobilize people anywhere in the country around a specific issue (like Gun Rights or Gun Control).</p>
        <p><strong>2)</strong> When you create or join a voting block, you’ll be able to invite friends to join it, get them pledged, and see who has voted, whether it’s early voting, absentee, or on election day.</p>
        <p><strong>3)</strong> You can join multiple blocks and anyone can join any voting block (these are not private areas).</p>
        <span class="close" tabindex="0"><i class="icon-close-brown"></i> CLOSE</span>
    </div>
    {% endif %}
    <div class="search">
        <div class="search-loading"></div>
        <h2>Find voting blocks</h2>
        <div class="search-input">
            <input type="text" placeholder="Search" />
            <span class="clear" tabindex="0"></span>
        </div>
        <div class="search-results">
            {% include '_voting_blocks_results.html' %}
        </div>
    </div>
    <div class="own">
        <h1>Rally your friends!</h1>
        <p class="info">Voting blocks are a powerful way to rally and organize friends who support your cause, website, or group to vote on November 6th.</p>
        <a class="btn btn-green btn-large create" href="{% url 'main:voting_blocks_create' %}"><i class="icon-plus"></i> Create Voting Block</a>
        <p>Before you create a new voting block, make sure one doesn’t exist already</p>
        {% include "_disclaimer.html" %}
        {% if my_voting_blocks %}
            <div class="mine">
                <h2>My Voting Blocks</h2>
                <ul>
                    {% for mvb in my_voting_blocks %}
                    <li class="cf">
                        <p class="name">{{ forloop.counter}}. <a href="{% url 'main:voting_blocks_item' id=mvb.id %}">{{ mvb.name }}</a></p>
                        <p class="count">{{ mvb.votingblockmember_set.count }} members</p>
                        {% thumbnail mvb.icon 56x36 crop as imgsrc %}
                        <img src="{% if imgsrc %}{{ imgsrc.url }}{% else %}{% static 'img/voting-block-56x36.png' %}{% endif %}">
                        <p class="description">{{ mvb.description }}</p>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>


</div>
{% endblock %}

{% block scripts %}
<script>
    SEARCH_URL = '{% url "main:voting_blocks_search" %}';
</script>
<script src="{% static 'js/voting_blocks.js' %}"></script>
{% endblock %}